#!/bin/bash

clear

# Colors
RED='\033[0;31m'
GRN='\033[0;32m'
CYN='\033[0;36m'
YEL='\033[1;33m'
NC='\033[0m' # No Color

# ASCII Art Banner
echo -e "${YEL}"
cat << "EOF"
   _____ _    _ _____ _    _          __  __ 
  / ____| |  | |_   _| |  | |   /\   |  \/  |
 | (___ | |__| | | | | |__| |  /  \  | \  / |
  \___ \|  __  | | | |  __  | / /\ \ | |\/| |
  ____) | |  | |_| |_| |  | |/ ____ \| |  | |
 |_____/|_|  |_|_____|_|  |_/_/    \_\_|  |_|
                                             
EOF
echo -e "${NC}"

# Subscribe animation
echo -ne "${GRN}🔥 Please Subscribe \n"
for i in {1..3}; do
  echo -ne "${CYN}Subscribing To SHIVAM"
  for dot in {1..3}; do
    echo -n "."
    sleep 0.3
  done
  echo -ne "\r                     \r"
done
echo -e "${GRN} Thanks for Subscribing! If Not Do It Rn${NC}\n"
sleep 1

#!/bin/bash

# panel theme install
cd /var/www/pterodactyl
php artisan down
curl -L https://github.com/Nookure/NookTheme/releases/latest/download/panel.tar.gz | tar -xzv
chmod -R 755 storage/* bootstrap/cache
composer install --no-dev --optimize-autoloader
php artisan view:clear
php artisan config:clear
php artisan migrate --seed --force
chown -R www-data:www-data /var/www/pterodactyl/*
php artisan queue:restart
php artisan up

# done
clear
